# Generated by Django 5.2 on 2026-04-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Customer's full name", max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, help_text="Customer's email address", max_length=254, null=True)),
                ('phone', models.CharField(db_index=True, help_text='Primary phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('city', models.CharField(blank=True, help_text='City', max_length=50)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about customer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether customer is active')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'created_at'], name='customers_c_name_f6ae37_idx'), models.Index(fields=['phone', 'email'], name='customers_c_phone_754260_idx')],
            },
        ),
    ]
