# Generated by Django 5.2 on 2026-04-07 11:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('job_type', models.CharField(choices=[('vehicle', 'Vehicle Refurbishment'), ('alloy', 'Alloy Wheels'), ('both', 'Vehicle & Alloy Wheels')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.TextField(help_text='Work to be performed')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, help_text='QR code for quick lookup', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='AlloyWheelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_size', models.CharField(help_text='Wheel size (e.g., 17x8)', max_length=10)),
                ('brand', models.CharField(blank=True, help_text='Wheel brand', max_length=50)),
                ('model', models.CharField(blank=True, help_text='Wheel model', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=4, help_text='Number of wheels')),
                ('damage_description', models.TextField(help_text='Description of damage/work needed')),
                ('finish_type', models.CharField(blank=True, help_text='Finish type (e.g., Gloss Black)', max_length=50)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alloy_wheels', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Alloy Wheel Details',
                'verbose_name_plural': 'Alloy Wheel Details',
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Upload job photo', upload_to='job_photos/%Y/%m/')),
                ('photo_type', models.CharField(choices=[('before', 'Before'), ('progress', 'Work in Progress'), ('after', 'After/Completed')], max_length=10)),
                ('caption', models.CharField(blank=True, help_text='Photo description', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Photo',
                'verbose_name_plural': 'Job Photos',
                'ordering': ['photo_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of service', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Service description')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['job', 'service_name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Vehicle make (e.g., Toyota)', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Camry)', max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Manufacturing year')),
                ('plate_number', models.CharField(db_index=True, help_text='License plate number', max_length=15)),
                ('color', models.CharField(blank=True, help_text='Vehicle color', max_length=30)),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Current mileage', null=True)),
                ('vin_number', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Vehicle Details',
                'verbose_name_plural': 'Vehicle Details',
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_date'], name='jobs_job_status_956555_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['customer', 'status'], name='jobs_job_custome_522329_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type', 'status'], name='jobs_job_job_typ_3f135c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['plate_number'], name='jobs_vehicl_plate_n_7484c8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['make', 'model'], name='jobs_vehicl_make_8a2423_idx'),
        ),
    ]
