# Generated by Django 5.2 on 2026-04-07 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('letter', 'Letter')], max_length=10)),
                ('scheduled_date', models.DateTimeField(help_text='When to send reminder')),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('responded', 'Customer Responded'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('message', models.TextField(help_text='Reminder message')),
                ('notes', models.TextField(blank=True, help_text='Follow-up notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('online', 'Online Payment')], max_length=15)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('partial', 'Partial Payment'), ('final', 'Final Payment'), ('refund', 'Refund')], max_length=10)),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Staff member who recorded payment', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['job', 'payment_date'], name='payments_pa_job_id_26c6f1_idx'), models.Index(fields=['payment_method', 'payment_date'], name='payments_pa_payment_97fe28_idx'), models.Index(fields=['payment_type', 'payment_date'], name='payments_pa_payment_93fd1e_idx')],
            },
        ),
    ]
